= Project Overview

This lab report documents the design, implementation, and measurement results of a UDP-based round-trip time (RTT) and latency jitter measurement system, built as part of the Distributed Embedded Systems course. The system targets two hardware nodes (Raspberry Pi 4) connected over a local network and is implemented in Rust. The full source code is available at #link("https://github.com/jakobgif/DRS-RT")[github.com/jakobgif/DRS-RT].

== Motivation

Real-time distributed systems must satisfy strict timing constraints. Understanding the round-trip latency between two nodes, and critically its worst-case behavior, is essential for validating whether a communication link meets those constraints. A single mean RTT value is insufficient; the full distribution, including rare tail latencies, must be captured and analyzed.

== System Architecture

The system follows a *Master / Echo* architecture:

- *Master node:* Sends a UDP packet, waits for a reply, and records the elapsed time as the round-trip time for that cycle. After all cycles complete, it writes the collected samples to a CSV file and a log file.
- *Echo node:* Listens for incoming UDP packets and immediately reflects each one back to the sender, without modification.

Both roles are delivered as a *single Rust binary*. The role is selected at runtime via a command-line argument (`master` or `echo`). All measurement parameters (target IP, port, cycle count, and receive timeout) are configurable via CLI flags.

== Measurement Discipline

To avoid the *probe effect* (where the act of measuring corrupts the measurement), all RTT samples are held in a pre-allocated in-memory buffer during the measurement loop. No file I/O, console output, or dynamic memory allocation occurs inside the loop. Samples are flushed to disk only after the loop has completed.

The Master uses `std::time::Instant` for timestamping, which maps to a monotonic hardware counter (ARM System Counter at 19.2 MHz on the Raspberry Pi 4, giving ~52 ns resolution). Timestamps are recorded immediately before the send and immediately after the receive, with no intervening logic.

== Analysis

A Python script consumes the CSV output produced by the Master. It computes the minimum, mean, and maximum RTT across all samples and generates a histogram with a logarithmic Y-axis so that rare worst-case tail latencies remain visible and are never obscured.

== AI Tool Usage

*Disclaimer: This report was written entirely by Claude (Anthropic). All text, structure, and analysis were generated by the AI assistant. The authors reviewed and approved the content.*

Claude Code (claude-sonnet-4-6, claude-haiku-4-5) was used throughout development for code generation, requirement analysis, and report writing. Token consumption was tracked using `ccusage` and is summarized below:

#table(
  columns: (auto, auto, auto, auto, auto, auto, auto),
  align: (left, right, right, right, right, right, right),
  table.header([*Date*], [*Input*], [*Output*], [*Cache Create*], [*Cache Read*], [*Total Tokens*], [*Cost (USD)*]),
  [2026-04-15], [8],       [523],     [21,319],  [70,032],     [91,882],     [\$0.11],
  [2026-04-19], [43],      [4,848],   [47,705],  [720,200],    [772,796],    [\$0.47],
  [2026-04-21], [32],      [2,391],   [44,524],  [689,469],    [736,416],    [\$0.41],
  [2026-04-22], [2,051],   [104,028], [179,394], [5,659,738],  [5,945,211],  [\$3.80],
  [2026-04-23], [176],     [68,588],  [211,922], [7,342,025],  [7,622,711],  [\$4.03],
  [2026-04-26], [43],      [11,678],  [76,930],  [650,805],    [739,456],    [\$0.66],
  [2026-04-28], [87],      [14,865],  [74,114],  [2,142,784],  [2,231,850],  [\$1.14],
  [*Total*],    [*2,440*], [*206,921*],[*655,908*],[*17,275,053*],[*18,140,322*],[*\$10.61*],
)

== Test Scenarios

Four test scenarios are defined to characterize the system under different load conditions:

#table(
  columns: (auto, auto, 1fr),
  table.header([*Scenario*], [*Cycles*], [*Load Condition*]),
  [T-1], [50,000],  [Normal operation (baseline)],
  [T-2], [50,000],  [High CPU load (background busy-loop)],
  [T-3], [50,000],  [High network load (second binary instance on a different port)],
  [T-4], [500,000], [Normal operation, long-term (captures rare tail latencies)],
)
