name: Build Report PDF

on:
  push:
    paths:
      - "docs/**"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Typst
        uses: typst-community/setup-typst@v5

      - name: Compile PDF
        run: typst compile docs/report/report.typ docs/report/report.pdf

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v7
        with:
          name: report
          path: docs/report/report.pdf
          archive: false
